<?php
/**
 * Copyright © CM.com. All rights reserved.
 * See LICENSE.txt for license details.
 */

/**
 * @see \CM\Payments\Block\Adminhtml\System\Config\Button\CheckLatestVersion
 * @var \CM\Payments\Block\Adminhtml\System\Config\Button\CheckLatestVersion $block
 *
 * @see \Magento\Framework\Escaper
 * @var \Magento\Framework\Escaper $escaper
 */
?>
<div class="cmpayments-result-version-wrapper"
     data-mage-init='{"CM_Payments/js/system/version": {}}'
     data-cmpayments-endpoint-url="<?= $escaper->escapeUrl($block->getLatestVersionCheckUrl()) ?>">
    <span><?= $escaper->escapeHtml($block->getCurrentVersion()); ?></span>
    <?= $block->getButtonHtml() ?>
    <div id="cmpayments-result-version"></div>
</div>