<?php
/**
 * Copyright © CM.com. All rights reserved.
 * See LICENSE.txt for license details.
 */

/**
 * @see \CM\Payments\Block\Adminhtml\System\Config\Button\CheckLatestVersion
 * @var \CM\Payments\Block\Adminhtml\System\Config\Button\CheckLatestVersion $block
 *
 * @see \Magento\Framework\Escaper
 * @var \Magento\Framework\Escaper $escaper
 */
?>
<div class="cmpayments-result-version-wrapper" data-bind="scope:'сmpayments-check-latest-version'">
    <span><?= $escaper->escapeHtml($block->getCurrentVersion()); ?></span>
    <?= $block->getButtonHtml() ?>
    <div class="cmpayments-result-version"></div>
</div>
<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "сmpayments-check-latest-version": {
                    "component": "CM_Payments/js/system/action/check-latest-version",
                    "config": {
                        "wrapperContainerSelector": ".cmpayments-result-version-wrapper",
                        "checkLatestVersionUrl": "<?= $escaper->escapeUrl($block->getCheckLatestVersionUrl()) ?>",
                        "resultContainerSelector": ".cmpayments-result-version"
                    }
                }
            }
        }
    }
}
</script>